import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/Aeonik-Medium.ttf",
  variable: "--font-geist-sans",
  weight: "400 500",
});
const geistMono = localFont({
  src: "./fonts/PPFragment-SerifRegular.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Archvis - Studio Innovative Arcihitecture and Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={` ${geistMono.className} antialiased overflow-x-hidden w-screen `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
